SELECT * FROM AG_NOTICE;
SELECT * FROM AG_MEMBER;

CREATE SEQUENCE NOTICE_NO_SEQ;
DROP SEQUENCE NOTICE_NO_SEQ;


DELETE FROM AG_NOTICE
WHERE NOTICE_NO =;

UPDATE AG_NOTICE
SET NOTICE_DELFLAG = 'X'
WHERE NOTICE_NO = 3;

UPDATE AG_MEMBER
SET MEMBER_ENABLED ='N'
WHERE MEMBER_ID = '6JA'

UPDATE AG_MEMBER
SET MEMBER_ENABLED = 'N'
WHERE MEMBER_ID = 'INGYU'

