SELECT TEST_SEQ.CURRVAL FROM DUAL;

SELECT * FROM EMP;

CREATE SEQUENCE TEST_SEQ1;
SELECT TEST_SEQ1.NEXTVAL FROM DUAL;

SELECT TEST_SEQ1.CURRVAL FROM DUAL;

CREATE TABLE TEST(
TEST_ID VARCHAR2(10) PRIMARY KEY
)


INSERT INTO TEST VALUES('TEST');
SELECT * FROM TEST;