CREATE SEQUENCE AG_MEMBERSEQ;
CREATE TABLE AG_MEMBER(
	MEMBER_ID VARCHAR2(50) PRIMARY KEY,
	MEMBER_TOKEN VARCHAR2(50),
	MEMBER_PW VARCHAR2(100) NOT NULL,
	MEMBER_NAME VARCHAR2(20) NOT NULL,
	MEMBER_EMAIL VARCHAR2(50) NOT NULL,
	MEMBER_ADDR VARCHAR2(4000) NOT NULL,
	MEMEBER_PHONE VARCHAR2(50) NOT NULL,
	MEMBER_ENABLED CHAR(1) CHECK(MEMBER_ENABLED IN('Y','N')),
	MEMBER_ROLE VARCHAR2(20) NOT NULL,
	MEMBER_SALT VARCHAR2(30)
	
);


INSERT INTO AG_MEMBER VALUES('INGYU1','1234','황','SDFDFS','DFSF','N','S','DF','a','1111',AG_MEMBERSEQ.NEXTVAL);

DROP TABLE AG_COMMENT;
ALTER TABLE AG_COMMENT ADD MEMBER_ID VARCHAR2(50);
ALTER TABLE AG_COMMENT MODIFY MEMBER_ID VARCHAR2(50) NOT NULL;
ALTER TABLE CHATLOG ADD CONSTRAINT CHAT_FK FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER(MEMBER_ID);
ALTER TABLE AG_COMMENT MODIFY (MEMBER_ENABLED DEFAULT 'N');
ALTER TABLE AG_MEMBER DROP COLUMN MEMBER_NO;
ALTER TABLE AG_MEMBER DROP COLUMN MEMEBER_PHONE;
SELECT * FROM AG_MEMBER;
DELETE FROM AG_MEMBER;



CREATE TABLE AG_CHATLOG(
	CHAT_NO NUMBER PRIMARY KEY,
	CHAT_DATE DATE NOT NULL,
	CHAT_CONTENT VARCHAR2(4000) NOT NULL,
	MEMBER_ID VARCHAR2(50), 
	CONSTRAINT CHAT_FK FOREIGN KEY(MEMBER_ID) REFERENCES AG_MEMBER(MEMBER_ID) 
	
);



CREATE TABLE AG_NOTICE(
	NOTICE_NO NUMBER PRIMARY KEY,
	NOTICE_TITLE VARCHAR2(2000) NOT NULL,
	NOTICE_CONTENT VARCHAR2(4000) NOT NULL,
	NOTICE_REGDATE DATE NOT NULL,
	NOTICE_HIT NUMBER NOT NULL,
	NOTICE_DELFLAG CHAR(1) NOT NULL,
	MEMBER_ID VARCHAR2(50),
	CONSTRAINT NOTICE_FK FOREIGN KEY(MEMBER_ID) REFERENCES AG_MEMBER(MEMBER_ID) 
);

CREATE TABLE AG_QNA(
	QNA_NO NUMBER PRIMARY KEY,
	QNA_TITLE VARCHAR2(2000) NOT NULL,
	QNA_CONTENT VARCHAR2(4000) NOT NULL,
	QNA_REGDATE DATE NOT NULL,
	QNA_HIT NUMBER NOT NULL,
	QNA_DELFLAG CHAR(1) NOT NULL,
	MEMBER_ID VARCHAR2(50),
	CONSTRAINT QNA_FK FOREIGN KEY(MEMBER_ID) REFERENCES AG_MEMBER(MEMBER_ID) 
);

CREATE TABLE AG_COMMENT(
	COMM_NO NUMBER PRIMARY KEY,
	COMM_CONTENT VARCHAR2(4000) NOT NULL,
	COMM_REGDATE DATE NOT NULL,
	COMM_STEP NUMBER NOT NULL,
	QNA_NO NUMBER,
	CONSTRAINT COMM_FK FOREIGN KEY(QNA_NO) REFERENCES AG_QNA(QNA_NO) 
);

CREATE TABLE AG_DONATION(
	DONA_NO NUMBER PRIMARY KEY,
	DONA_BILL NUMBER NOT NULL,
	DONA_DATE DATE NOT NULL,
	MEMBER_ID VARCHAR2(50),
	CONSTRAINT DONA_FK FOREIGN KEY(MEMBER_ID) REFERENCES AG_MEMBER(MEMBER_ID) 
);

CREATE TABLE AG_PRESCRIPTION(
	MEMBER_ID VARCHAR2(50) PRIMARY KEY,
	PRES_NO NUMBER NOT NULL,
	PRES_MEDINAME VARCHAR2(200) NOT NULL,
	PRES_DATE DATE NOT NULL,
	PRES_VIEW VARCHAR2(200) NOT NULL,
	CONSTRAINT PRES_FK FOREIGN KEY(MEMBER_ID) REFERENCES AG_MEMBER(MEMBER_ID) 
);

CREATE TABLE AG_SCHEDULE(
	SCHE_NO NUMBER PRIMARY KEY,
	MEMBER_ID VARCHAR2(50),
	SCHE_TITLE VARCHAR2(200) NOT NULL,
	SCHE_CONTENT VARCHAR2(4000) NOT NULL,
	SCHE_MDATE DATE NOT NULL,
	SCHE_REGDTAE DATE NOT NULL,
	CONSTRAINT SCHE_FK FOREIGN KEY(MEMBER_ID) REFERENCES AG_MEMBER(MEMBER_ID) 
);

INSERT INTO AG_DONATION VALUES(1,4000,'20-07-12','INGYU'); 

