SELECT * FROM AG_DONATION;

SELECT AG_DONATIONSEQ.CURRVAL FROM AG_DONATION;
SELECT AG_DONATIONSEQ.NEXTVAL FROM DUAL;

DELETE * FROM AG_DONATION ORDER BY DONA_NO;

SELECT DONA_NO, MEMBER_ID, DONA_BILL, DONA_DATE
FROM AG_DONATION
WHERE MEMBER_ID = 'test2';